export enum KnifeMidReleaseFinishes {
  BlueSteel = "Blue Steel",
  BorealForest = "Boreal Forest",
  CaseHardened = "Case Hardened",
  CrimsonWeb = "Crimson Web",
  DamascusSteel = "Damascus Steel",
  Doppler = "Doppler",
  Fade = "Fade",
  ForestDDPAT = "Forest DDPAT",
  MarbleFade = "Marble Fade",
  NightStripe = "Night Stripe",
  RustCoat = "Rust Coat",
  SafariMesh = "Safari Mesh",
  Scorched = "Scorched",
  Slaughter = "Slaughter",
  Stained = "Stained",
  TigerTooth = "Tiger Tooth",
  Ultraviolet = "Ultraviolet",
  UrbanMasked = "Urban Masked",
  Vanilla = "Vanilla",
}
