export enum KnifeNewReleaseFinishes {
	BlueSteel = "Blue Steel",
	BorealForest = "Boreal Forest",
	CaseHardened = "Case Hardened",
	CrimsonWeb = "Crimson Web",
	Fade = "Fade",
	ForestDDPAT = "Forest DDPAT",
	NightStripe = "NightStripe",
	SafariMesh = "Safari Mesh",
	Scorched = "Scorched",
	Slaughter = "Slaughter",
	Stained = "Stained",
	UrbanMasked = "Urban Masked",
	Vanilla = "Vanilla",
}
