export enum KnifeStandardFinishes {
  Autotronic = "Autotronic",
  BlackLaminate = "Black Laminate",
  BlueSteel = "Blue Steel",
  BorealForest = "Boreal Forest",
  BrightWater = "Bright Water",
  CaseHardened = "Case Hardened",
  CrimsonWeb = "Crimson Web",
  DamascusSteel = "Damascus Steel",
  Doppler = "Doppler",
  Fade = "Fade",
  ForestDDPAT = "Forest DDPAT",
  Freehand = "Freehand",
  GammaDoppler = "Gamma Doppler",
  Lore = "Lore",
  MarbleFade = "Marble Fade",
  Night = "Night",
  RustCoat = "Rust Coat",
  SafariMesh = "Safari Mesh",
  Scorched = "Scorched",
  Slaughter = "Slaughter",
  Stained = "Stained",
  TigerTooth = "Tiger Tooth",
  Ultraviolet = "Ultraviolet",
  UrbanMasked = "Urban Masked",
  Vanilla = "Vanilla",
}
