export enum M249Skins {
  Aztec = "Aztec",
  BlizzardMarbleized = "Blizzard Marbleized",
  ContrastSpray = "Contrast Spray",
  DeepRelief = "Deep Relief",
  Downtown = "Downtown",
  EmeraldPoisonDart = "Emerald Poison Dart",
  GatorMesh = "Gator Mesh",
  Humidor = "Humidor",
  ImpactDrill = "Impact Drill",
  Jungle = "Jungle",
  JungleDDPAT = "Jungle DDPAT",
  Magma = "Magma",
  MidnightPalm = "Midnight Palm",
  NebulaCrusader = "Nebula Crusader",
  OSIPR = "O.S.I.P.R.",
  Predator = "Predator",
  ShippingForecast = "Shipping Forecast",
  Spectre = "Spectre",
  Submerged = "Submerged",
  SystemLock = "System Lock",
  Warbird = "Warbird",
}
