export enum NegevSkins {
  AnodizedNavy = "Anodized Navy",
  ArmySheen = "Army Sheen",
  BoroqueSand = "Boroque Sand",
  Bratatat = "Bratatat",
  Bulkhead = "Bulkhead",
  CaliCamo = "CaliCamo",
  Dazzle = "Dazzle",
  DesertStrike = "Desert-Strike",
  devtexture = "dev_texture",
  DropMe = "Drop Me",
  Infrastructure = "Infrastructure",
  Lionfish = "Lionfish",
  Loudmouth = "Loudmouth",
  ManOWar = "Man-o'-war",
  Mjolnir = "Mjölnir",
  NuclearWaste = "Nuclear Waste",
  Palm = "Palm",
  PhoenixStencil = "Phoenix Stencil",
  PowerLoader = "Power Loader",
  Prototype = "Prototype",
  Terrain = "Terrain",
  Ultralight = "Ultralight",
}
