export enum MP5Skins {
	AcidWash = "Acid Wash",
	Agent = "Agent",
	AutumnTwilly = "Autumn Twilly",
	BambooGarden = "Bamboo Garden",
	ConditionZero = "Condition Zero",
	CoProcessor = "Co-Processor",
	DesertStrike = "Desert Strike",
	DirtDrop = "Dirt Drop",
	Gauss = "Gauss",
	Kitbash = "Kitbash",
	LabRats = "Lab Rats",
	Liquidation = "Liquidation",
	NecroJr = "Necro Jr.",
	Nitro = "Nitro",
	OxideOasis = "Oxide Oasis",
	Phosphor = "Phosphor",
}
