import db from "@/utils/db";
console.log("Turso token set:", !!Bun.env.TURSO_TOKEN);
console.log("Communicating via:", db?.protocol);
const res = await db?.execute("SELECT * FROM tracked_skins");
console.log("Received tracked_skins response!");
console.log(res?.toJSON());
console.log("\n\n\n");
const priceHistoryRes = await db?.execute("SELECT * FROM price_history");
console.log("Received price_history response!");
console.log(priceHistoryRes?.toJSON());