export enum SCAR20Skins {
	ArmySheen = "Army Sheen",
	Assault = "Assault",
	Bloodsport = "Bloodsport",
	Blueprint = "Blueprint",
	Brass = "Brass",
	CarbonFiber = "Carbon Fiber",
	Cardiac = "Cardiac",
	Contractor = "Contractor",
	CrimsonWeb = "Crimson Web",
	Cyrex = "Cyrex",
	Emerald = "Emerald",
	Enforcer = "Enforcer",
	Fragments = "Fragments",
	GreenMarine = "Green Marine",
	Grotto = "Grotto",
	JungleSlipstream = "Jungle Slipstream",
	MagnaCarta = "Magna Carta",
	Outbreak = "Outbreak",
	Palm = "Palm",
	Poultrygeist = "Poultrygeist",
	Powercore = "Powercore",
	SandMesh = "Sand Mesh",
	SplashJam = "Splash Jam",
	StoneMosaico = "Stone Mosaico",
	Storm = "Storm",
	Torn = "Torn",
}
