import {
  AK47Skins,
  AUGSkins,
  AWPSkins,
  BayonetSkins,
  BloodhoundGlovesSkins,
  BowieKnifeSkins,
  BrokenFangGlovesSkins,
  ButterflyKnifeSkins,
  CZ75AutoSkins,
  ClassicKnifeSkins,
  DesertEagleSkins,
  DriverGlovesSkins,
  DualBerettasSkins,
  FAMASSkins,
  FalchionKnifeSkins,
  FiveSevenSkins,
  FlipKnifeSkins,
  G3SG1Skins,
  GalilSkins,
  Glock18Skins,
  Gloves,
  GutKnifeSkins,
  HandWrapsSkins,
  HuntsmanKnifeSkins,
  HydraGlovesSkins,
  KarambitSkins,
  Knife,
  M4A1SSkins,
  M4A4Skins,
  M9BayonetSkins,
  M249Skins,
  MAC10Skins,
  MAG7Skins,
  MP5Skins,
  MP7Skins,
  MP9Skins,
  MotoGlovesSkins,
  NavajaKnifeSkins,
  NegevSkins,
  NomadKnifeSkins,
  NovaSkins,
  P90Skins,
  P250Skins,
  P2000Skins,
  PPBizonSkins,
  ParacordKnifeSkins,
  R8RevolverSkins,
  SCAR20Skins,
  SG553Skins,
  SSG08Skins,
  SawedOffSkins,
  ShadowDaggersSkins,
  SkeletonKnifeSkins,
  SpecialistGlovesSkins,
  SportGlovesSkins,
  StilettoKnifeSkins,
  SurvivalKnifeSkins,
  TalonKnifeSkins,
  Tec9Skins,
  UMP45Skins,
  USPSSkins,
  UrsusKnifeSkins,
  Weapon,
  XM1014Skins,
  STSkin,
} from "@skintracker/types/src";

export const ALL_SUPPORTED_WEAPONS: string[] = [
  ...Object.values(Gloves),
  ...Object.values(Knife),
  ...Object.values(Weapon),
];

export const WEAPON_STRING_TO_SKINS: Record<string, string[]> = {
  "Bloodhound Gloves": Object.values(BloodhoundGlovesSkins),
  "Broken Fang Gloves": Object.values(BrokenFangGlovesSkins),
  "Driver Gloves": Object.values(DriverGlovesSkins),
  "Hand Wraps": Object.values(HandWrapsSkins),
  "Hydra Gloves": Object.values(HydraGlovesSkins),
  "Moto Gloves": Object.values(MotoGlovesSkins),
  "Specialist Gloves": Object.values(SpecialistGlovesSkins),
  "Sport Gloves": Object.values(SportGlovesSkins),
  Bayonet: Object.values(BayonetSkins),
  "Butterfly Knife": Object.values(ButterflyKnifeSkins),
  "Bowie Knife": Object.values(BowieKnifeSkins),
  "Classic Knife": Object.values(ClassicKnifeSkins),
  "Falchion Knife": Object.values(FalchionKnifeSkins),
  "Flip Knife": Object.values(FlipKnifeSkins),
  "Gut Knife": Object.values(GutKnifeSkins),
  "Huntsman Knife": Object.values(HuntsmanKnifeSkins),
  Karambit: Object.values(KarambitSkins),
  "M9 Bayonet": Object.values(M9BayonetSkins),
  "Navaja Knife": Object.values(NavajaKnifeSkins),
  "Nomad Knife": Object.values(NomadKnifeSkins),
  "Paracord Knife": Object.values(ParacordKnifeSkins),
  "Shadow Daggers": Object.values(ShadowDaggersSkins),
  "Skeleton Knife": Object.values(SkeletonKnifeSkins),
  "Stiletto Knife": Object.values(StilettoKnifeSkins),
  "Survival Knife": Object.values(SurvivalKnifeSkins),
  "Talon Knife": Object.values(TalonKnifeSkins),
  "Ursus Knife": Object.values(UrsusKnifeSkins),
  "AK-47": Object.values(AK47Skins),
  AUG: Object.values(AUGSkins),
  AWP: Object.values(AWPSkins),
  "CZ75-Auto": Object.values(CZ75AutoSkins),
  "Desert Eagle": Object.values(DesertEagleSkins),
  "Dual Berettas": Object.values(DualBerettasSkins),
  FAMAS: Object.values(FAMASSkins),
  "Five-SeveN": Object.values(FiveSevenSkins),
  G3SG1: Object.values(G3SG1Skins),
  "Galil AR": Object.values(GalilSkins),
  "Glock-18": Object.values(Glock18Skins),
  M249: Object.values(M249Skins),
  "M4A1-S": Object.values(M4A1SSkins),
  M4A4: Object.values(M4A4Skins),
  "MAC-10": Object.values(MAC10Skins),
  "MAG-7": Object.values(MAG7Skins),
  "MP5-SD": Object.values(MP5Skins),
  MP7: Object.values(MP7Skins),
  MP9: Object.values(MP9Skins),
  Negev: Object.values(NegevSkins),
  Nova: Object.values(NovaSkins),
  P2000: Object.values(P2000Skins),
  P250: Object.values(P250Skins),
  P90: Object.values(P90Skins),
  "PP-Bizon": Object.values(PPBizonSkins),
  "R8 Revolver": Object.values(R8RevolverSkins),
  "Sawed-Off": Object.values(SawedOffSkins),
  "SCAR-20": Object.values(SCAR20Skins),
  "SG 553": Object.values(SG553Skins),
  "SSG 08": Object.values(SSG08Skins),
  "Tec-9": Object.values(Tec9Skins),
  "UMP-45": Object.values(UMP45Skins),
  "USP-S": Object.values(USPSSkins),
  XM1014: Object.values(XM1014Skins),
};

export const ALL_SUPPORTED_WEAPON_SKIN_STRINGS: string[] =
  ALL_SUPPORTED_WEAPONS.flatMap((item) => {
    if (item in WEAPON_STRING_TO_SKINS) {
      return WEAPON_STRING_TO_SKINS[item].map((skin) => `${item} | ${skin}`);
    }
    return [];
  });
  