export enum R8RevolverSkins {
  AmberFade = "Amber Fade",
  BananaCannon = "Banana Cannon",
  Blaze = "Blaze",
  BoneForged = "Bone Forged",
  BoneMask = "Bone Mask",
  CanalSpray = "Canal Spray",
  Crazy8 = "Crazy 8",
  CrimsonWeb = "Crimson Web",
  DesertBrush = "Desert Brush",
  Fade = "Fade",
  Grip = "Grip",
  Inlay = "Inlay",
  Junkyard = "Junkyard",
  LlamaCannon = "Llama Cannon",
  Memento = "Memento",
  Night = "Night",
  Nitro = "Nitro",
  PhoenixMarker = "Phoenix Marker",
  Reboot = "Reboot",
  SkullCrusher = "Skull Crusher",
  Survivalist = "Survivalist",
}
